config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#monthly"

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create]
  resources :menu, only: :index
  resources :comments, only: :new
  resources :stamps, only: :create

  resources :tasks, only: [:index, :new, :create, :show] do
    resources :reports, only: [:new, :create], shallow: true do
      resources :comments, only: :create
    end
    collection do
      get 'monthly'
      get 'weekly'
      get 'daily'
    end
  end


  # adminがUserを作成する仕様かと判断しこめんとアウト
  # get 'sign_up' => 'users#new', as: :sign_up
  get 'sign_in' => 'user_sessions#new', as: :sign_in
  post 'sign_out' => 'user_sessions#destroy', as: :sign_out
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_one :report

  attr_accessor :month, :week, :date, :start_time, :finish_time

  enum kind: {
    daily: 0,
    weekly: 1,
    monthly: 2
  }

  validates :title, presence: true
  validates :kind, presence: true
  validates :start_datetime, presence: true
  validates :finish_datetime, presence: true
  validates :user_id, presence: true
  validate  :start_datetime_should_be_less_than_finish_datetime

  include DateTimeConvertable

  scope :dones, -> { select{ |t| t.report.present? } }

  def self.fetch_tasks_for_the_month(date, user, kind)
    first_date = DateTime.new(date.year, date.month, 1)
    last_date = DateTime.new(date.year, date.month, -1, -1, -1, -1, -1)
    self.where(kind: kind).where("start_datetime between ? and ?", first_date, last_date).where(user_id: user.id).order("start_datetime ASC")
  end

  def self.fetch_tasks_for_the_week(date, user, kind)
    datetime = date.to_datetime
    first_date = datetime.beginning_of_week
    last_date = datetime.end_of_week
    self.where(kind: kind).where("start_datetime between ? and ?", first_date, last_date).where(user_id: user.id).order("start_datetime ASC")
  end

  private

  def start_datetime_should_be_less_than_finish_datetime
    errors.add(:start_date, "をfinish_dateより前に入力してください") unless start_datetime <= finish_datetime
  end

  # 日付処理: 参考文献
  # https://qiita.com/prgseek/items/c0fc2ffc8e1736348486
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  include Banken

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to action: :new
    else
      render "new"
    end
  end

  def show
    task = Task.find(params[:id])
    @task = task.decorate
    @report = task.report.decorate if task.report
    @comments = @report.comments if @report && @report.comments
    authorize! @task
  end

  def monthly
    @date = params[:date].try(:to_date) || Date.today
    @prev_month = @date.advance(months: -1)
    @next_month = @date.advance(months: 1)
    daily_tasks = Task.fetch_tasks_for_the_month(@date, current_user, :daily)
    @days = MonthlyCalendarService.new(@date, daily_tasks).to_a.flatten
    @monthly_tasks = Task.fetch_tasks_for_the_month(@date, current_user, :monthly)
  end

  def weekly
    @date = params[:date].try(:to_date) || Date.today
    @prev_week = @date.advance(weeks: -1)
    @next_week = @date.advance(weeks: 1)
    daily_tasks = Task.fetch_tasks_for_the_week(@date, current_user, :daily)
    @days = WeeklyCalendarService.new(@date, daily_tasks).to_a.flatten
    @weekly_tasks = Task.fetch_tasks_for_the_week(@date, current_user, :weekly)
  end

  def daily
  end

  private
    def task_params
      params.require(:task).permit(:title, :kind, :start_time, :finish_time, :date, :week, :month).merge(user_id: current_user.id)
    end
end

app/views/tasks/_form.haml
.row.justify-content-md-center
  .col-md-4
    = form_for @task do |f|
      - if @task.errors.any?
        #error_explanation
          / %h2= @task.errors.count.to_s + "件のエラーが発生しています"
          %ul
            - @task.errors.full_messages.each do |message|
              %li= message

      %h5.title タスク名
      .input-group.form-group-no-border.input-lg
        = f.text_field :title, class: 'form-control', placeholder: 'タスク名を入力', required: true

      / %h5.title タスク期間選択
      .row#task-kind-selector
        .radio.col-4
          = f.radio_button :kind, :monthly
          = f.label :monthly, for: 'task_kind_monthly'
        .radio.col-4
          = f.radio_button :kind, :weekly
          = f.label :weekly, for: 'task_kind_weekly'
        .radio.col-4
          = f.radio_button :kind, :daily, checked: true
          = f.label :daily, for: 'task_kind_daily'

      #schedule-form
        #monthly.hidden
          = render partial: "shared/forms/month", locals: { f: f }
        #weekly.hidden
          = render partial: "shared/forms/week", locals: { f: f }
        #daily
          = render partial: "shared/forms/day", locals: { f: f }

      .samp
        = f.submit "登録", class: 'btn btn-uptech btn-round btn-lg btn-block'

:javascript
  selectors = document.getElementsByName('task[kind]')
  scheduleForm = document.getElementById('schedule-form')
  new ScheduleForm(selectors, scheduleForm).onChangeSelector()

app/views/tasks/daily.haml
.section
  .container.calendar-weekly
    .month
      %ul
        %li.prev
          ❮
          %span>< 昨日
        %li.next
          %span>< 明日
          ❯
        %li
          2月3日(土)
          %br/
          %span{:style => "font-size:12px"} 2017
    .time
      %table.calendar.table.table-bordered
        %tbody
          %tr
            %td 08:00
            %td.has-events{:rowspan => "1"}
              .row-fluid.practice{:style => "width: 99%; height: 100%;"}
                %span.title Calculus 1
                %span.lecturer
                  %a
                    Mrs.
                    Ak
                %span.location 54/125
          %tr
            %td 08:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 09:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 09:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 10:00
            %td.has-events{:rowspan => "4"}
              .row-fluid.lecture{:style => "width: 99%; height: 100%;"}
                %span.title Combinatorics
                %span.lecturer
                  %a
                    Prof.
                    Someone
                %span.location 23/111
          %tr
            %td 10:30
          %tr
            %td 11:00
          %tr
            %td 11:30
          %tr
            %td 12:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 12:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 13:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 13:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 14:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 14:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 15:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 15:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 16:00
            %td.has-events{:rowspan => "4"}
              .row-fluid.practice{:style => "width: 99%; height: 100%;"}
                %span.title Calculus 1
                %span.lecturer
                  %a
                    Mrs.
                    Ak
                %span.location 54/125
          %tr
            %td 16:30
          %tr
            %td 17:00
          %tr
            %td 17:30
          %tr
            %td 18:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 18:30
            %td.no-events{:rowspan => "1"}
          %tr
            %td 19:00
            %td.no-events{:rowspan => "1"}
          %tr
            %td 19:30
            %td.no-events{:rowspan => "1"}

app/views/tasks/index.haml
- if flash[:error]
  %div
    = flash[:error]
= link_to "タスク作成", new_task_path

%h1
  タスク一覧
%ul
  - @tasks.each do |task|
    %li
      = task.title
      = link_to "詳細", task_path(task)

app/views/tasks/monthly.haml
.section
  .container.calendar-monthly
    .month
      %ul
        %li.prev
          = link_to monthly_tasks_path(date: @prev_month) do
            ❮
        %li.next
          = link_to monthly_tasks_path(date: @next_month) do
            ❯
        %li
          = @date.strftime("%B")
          %br/
          %span{:style => "font-size:12px"}= @date.strftime("%Y")
    %ul.weekdays
      %li Mo
      %li Tu
      %li We
      %li Th
      %li Fr
      %li Sa
      %li Su
    %ul.days
      - @days.each do |day|
        %li
          - if day[:has_task]
            = link_to "#" do
              %span.active= day[:date]
          - else
            = link_to "#" do
              = day[:date]
    %ul.tasklist
      - @monthly_tasks.each do |task|
        %li
          %span 月タスク
          = task.title

app/views/tasks/new.haml
%header.header-nav.navbar.navbar-expand-lg.bg-uptech.fixed-top
  .col-12.text-center
    タスク登録

.section
  .container
    = render 'form'

app/views/tasks/show.haml
%header.header-nav.navbar.navbar-expand-lg.bg-uptech.fixed-top
  .left-nav.col-3
    %a{:onclick => "history.back()", :href => '#'} 戻る
  .col-6.text-center
    タスク詳細
  .right-nav.col-3
    = link_to '編集' #

%section.section.task-show
  .task-details
    %ul
      %li
        %h4.title タスク名
        %p
          = @task.title
          %span
            = @task.kind
        %h4.title 予定日時
        %p
          = @task.slashed_start_datetime + "~" + @task.slashed_finish_datetime
  - unless @report
    .task-actions
      .row
        .col-6
          = link_to new_task_report_path(@task), class: 'btn btn-uptech btn-round btn-lg btn-block' do
            持ち越し
        .col-6
          = link_to new_task_report_path(@task), class: 'btn btn-uptech btn-round btn-lg btn-block' do
            報告
  - if @report
    .task-comments
      %h5 実行日時
      %p= "#{@report.start_to_finish}"
  - if @comments
    .task-comments
      %h5.title 上長からのコメント
      - @comments.each do |comment|
        %p= comment.text
        .task-comments-status
          %ul
            %li 上長からいいねされました
            %li 上長から伸びしろありと評価されています

app/views/tasks/weekly.haml
.section
  .container.calendar-weekly
    .month
      %ul
        %li.prev
          = link_to weekly_tasks_path(date: @prev_week) do
            ❮
            / %span>< 前週
        %li.next
          = link_to weekly_tasks_path(date: @next_week) do
            /
            ❯
        %li
          = @date.beginning_of_week.strftime("%m/%d") + " ~ " + @date.end_of_week.strftime("%m/%d")
          %br/
          %span{:style => "font-size:12px"}= @date.year
    .week-day
      %ul
        - @days.each do |day|
          %li
            .day-title= day[:date]
            - unless day[:tasks].empty?
              - day[:tasks].each do |task|
                .day-content
                  = link_to task_path(task) do
                    = task.decorate.start_time_to_finish_time + " / " + task.title
            - else
              .day-content
                No task
        / %li
        /   .day-title 2月3日(月)
        /   .day-content 終日
        / %li
        /   .day-title 2月4日(火)
        /   .day-content 終日
        / %li
        /   .day-title 2月5日(水)
        /   .day-content 終日
        / %li
        /   .day-title 2月6日(木)
        /   .day-content 終日
        / %li
        /   .day-title 2月7日(金)
        /   .day-content 終日
        / %li
        /   .day-title 2月8日(土)
        /   .day-content 終日
        / %li
        /   .day-title 2月9日(日)
        /   .day-content 終日
    %ul.tasklist
      - @weekly_tasks.each do |task|
        %li
          %span 週タスク
          = task.title