config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#monthly"

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create]
  resources :menu, only: :index
  resources :comments, only: :new
  resources :stamps, only: :create

  resources :tasks, only: [:index, :new, :create, :show] do
    resources :reports, only: [:new, :create], shallow: true do
      resources :comments, only: :create
    end
    collection do
      get 'monthly'
      get 'weekly'
      get 'daily'
    end
  end


  # adminがUserを作成する仕様かと判断しこめんとアウト
  # get 'sign_up' => 'users#new', as: :sign_up
  get 'sign_in' => 'user_sessions#new', as: :sign_in
  post 'sign_out' => 'user_sessions#destroy', as: :sign_out
end

app/views/shared/_footer.haml
%ul.bottom-navigation
  %li
    = link_to '月', monthly_tasks_path, class: "#{'active' if action_name == 'monthly'}"
  %li
    = link_to '週', weekly_tasks_path, class: "#{'active' if action_name == 'weekly'}"
  %li
    = link_to '日', daily_tasks_path, class: "#{'active' if action_name == 'daily'}"
  %li
    = link_to '/tasks/new', class: "#{'active' if controller_name == 'tasks' && action_name == 'new'} " do
      %span.now-ui-icons.ui-1_simple-add
  %li
    = link_to menu_index_path, class: "#{'active' if controller_name == 'menu'}" do
      %span.now-ui-icons.design_bullet-list-67

app/views/shared/_header.haml
%nav.navbar.navbar-expand-lg.bg-uptech.fixed-top{"color-on-scroll" => "400"}
  .container
    .navbar-translate
      %a.navbar-brand{href: "/"}
        = image_tag 'logo-white.svg', alt: 'Uptech'