config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#monthly"

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create]
  resources :menu, only: :index
  resources :comments, only: :new
  resources :stamps, only: :create

  resources :tasks, only: [:index, :new, :create, :show] do
    resources :reports, only: [:new, :create], shallow: true do
      resources :comments, only: :create
    end
    collection do
      get 'monthly'
      get 'weekly'
      get 'daily'
    end
  end


  # adminがUserを作成する仕様かと判断しこめんとアウト
  # get 'sign_up' => 'users#new', as: :sign_up
  get 'sign_in' => 'user_sessions#new', as: :sign_in
  post 'sign_out' => 'user_sessions#destroy', as: :sign_out
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: :destroy

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to root_path, notice: 'ログインに成功しました'
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to :sign_in, notice: 'ログアウトしました。'
  end
end

app/views/user_sessions/_form.haml
= form_with url: user_sessions_path do |f|
  .header.header-primary.text-center
    .logo-container
      = image_tag 'logo-black.svg', alt: 'Uptech'
      ログイン
    .content
      .input-group.form-group-no-border.input-lg
        %span.input-group-addon
          %i.now-ui-icons.ui-1_email-85
        = f.email_field :email, class: 'form-control', placeholder: 'メールアドレスを入力'
      .input-group.form-group-no-border.input-lg
        %span.input-group-addon
          %i.now-ui-icons.ui-1_lock-circle-open
        = f.password_field :password,  class: 'form-control', placeholder: 'パスワードを入力'

    .footer.text-center
      = f.submit :ログイン, class: 'btn btn-uptech btn-round btn-lg btn-block'
    .pull-left
      %h6
        = link_to '/users/new', class: 'link' do
          アカウントを作成する

app/views/user_sessions/new.html.haml
.page-header
  .container
    .col-md-4.content-center
      .card.card-login.card-plain
        = render 'form'